# Generated by Django 6.0.3 on 2026-03-08 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="commission",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
